### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#12]
Was just thinking we should think of a cool name of this?

Reconquestor?

**Comment by jkosem** [comment]
@JGL Take your pick:

After Forever
Super air

**Comment by jkosem** [comment]
@JGL I'm leaning towards After Forever but Supernaut sounds way more like a badass product some how

**Comment by JGL** [comment]
A spanish word?

**Comment by jkosem** [comment]
Supernaut +1 but After Forever sounds like the rag tag bunch of dudes on the internet saving cultural heritage.

**Comment by jkosem** [comment]
![Uploading Screenshot 2021-03-11 at 17.03.37.png…]()

**Comment by jkosem** [comment]
Supernina?

<img width="823" alt="Screenshot 2021-03-11 at 17 04 18" src="https://user-images.githubusercontent.com/495102/110816657-d32def00-828b-11eb-9dd9-67ade2e1502c.png">

**Comment by JGL** [comment]
Wine and Swine is good!
