### ISSUE TITLE
Jim as admin on repo?

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#13]
@JGL Mind making me an admin on this thing? I can't change the labels, etc. I promise I won't delete the whole thing or sell it for millions. Well maybe.

**Comment by JGL** [comment]
You are already a collaborator on the project?

**Comment by JGL** [comment]
Is it working now?

**Comment by jkosem** [comment]
Nope, no Settings

Supposed to look like this
<img width="806" alt="Screenshot 2020-09-03 at 13 48 56" src="https://user-images.githubusercontent.com/495102/92111219-4726a080-edec-11ea-874b-16ec9173df84.png">

No panic for now, but if you can, that would be cool.

**Comment by JGL** [comment]
All I can do is invite collaborators. That's it. You are already that. What can't you do?

**Comment by JGL** [comment]
You've already commited to this repo. What else is there?

**Comment by jkosem** [comment]
It’s fine. Leave it. Close at will.
