### ISSUE TITLE
Model-Viewer

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#20]
The alternative to A-Frame is what looks to be the Google Model Viewer.

https://modelviewer.dev/examples/augmented-reality.html

It works quite well, and so far working on Safari, FF and Brave (Chrome).

On iOS it shows the icon for AR (Reality Composer) which looks like this

![IMG_E72DE1CA4D06-1](https://user-images.githubusercontent.com/495102/95464964-db9b9a00-097a-11eb-86d3-ed4eaefd9a89.png)

**Comment by jkosem** [comment]
@JGL https://9to5google.com/2020/11/10/google-3d-animals-list/

**Comment by JGL** [comment]
https://cwervo.com/writing/quicklook-web/

**Comment by JGL** [comment]
I think it's both in this article: <https://cwervo.com/writing/quicklook-web/>

**Comment by jkosem** [comment]
From that article, it looks like it's not supported in-app browser on iOS 12. That would mean us right?

**Comment by JGL** [comment]
We are going purely web and waypoint based for first version. Might re-open for v2
