### ISSUE TITLE
Useful links

### ISSUE THREAD

**Issue by apluskowski** [JGL/WalkingTourClient#22]
A couple of links I've come across that may be useful:

This is a map based search engine connected with heritage: https://peripleo.pelagios.org/ 

Mobile apps connected with "Cathar castles" in the eastern Pyrenees: https://www.payscathare.org/les-applis

**Comment by jkosem** [comment]
Bravo @apluskowski You added an issue and didn't even catch it.

**Comment by jkosem** [comment]
@apluskowski I'm really curious what they mean by "360 geo-tagged sphere" but looks to do a lot of the same sort of things. However, doesn't look to do any geo tracking though either.

**Comment by JGL** [comment]
I'm closing and adding to the wiki!
