### ISSUE TITLE
Add different kinds of multimedia to test - video and sound as priority

### ISSUE THREAD

**Issue by JGL** [JGL/WalkingTourClient#27]
This is in response to #9

**Comment by jkosem** [comment]
I'm assuming via URL here?

<img width="914" alt="Screenshot 2021-03-11 at 17 09 15" src="https://user-images.githubusercontent.com/495102/110817365-8565b680-828c-11eb-9ef3-7caf6f4a96ba.png">

**Comment by JGL** [comment]
Yes, but it will display natively in the Client.
