### ISSUE TITLE
Should we have voice synthesis? 

### ISSUE THREAD

**Issue by JGL** [JGL/WalkingTourClient#28]
https://aws.amazon.com/polly/

And what about at least English and Spanish as languages?

**Comment by jkosem** [comment]
@apluskowski What do you think?

**Comment by apluskowski** [comment]
Yes, if possible!

**Comment by jkosem** [comment]
This would be a good way around having to do voice acting on no budget I suppose. Free account?

**Comment by apluskowski** [comment]
Sounds ideal.

**Comment by JGL** [comment]
I'm going to go with just English text for V1, but translations into spanish for v2 for sure.
