### ISSUE TITLE
Let's try ar.js out again - they seemed to have added location based code?

### ISSUE THREAD

**Issue by JGL** [JGL/WalkingTourClient#29]
https://github.com/AR-js-org/AR.js#location-based-example

Location based?

**Comment by jkosem** [comment]
Last update was 6 months ago so this thing should be maybe still alive.

What would that give us? It gives lat and long but not altitude. So where or how high does the thing go?

**Comment by JGL** [comment]
V3 only! Concentrating on map based with geolocation and multimedia for V1
