### ISSUE TITLE
Playcanvas investigation

### ISSUE THREAD

**Issue by JGL** [JGL/WalkingTourClient#30]
https://twitter.com/mrmaxm/status/1330232934192853003
https://twitter.com/mrmaxm/status/1329151944540254208
Image tracking in playcanvas
https://github.com/playcanvas/engine/pull/2574
https://github.com/immersive-web/marker-tracking/blob/main/explainer.md
https://playcanvas.com/features
Open source?

https://github.com/playcanvas/engine

**Comment by jkosem** [comment]
This is obviously amazing. Were you thinking for AR tracking?

**Comment by JGL** [comment]
Yes for v2, but not for this one
