### ISSUE TITLE
Starting with wine and going backwards

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#4]
@JGL 

Was thinking another way to frame it might be to do it sort of in reverse, starting from the wine and working backwards through the story. You could use the bottle even (QR?) to activate it perhaps and then be led back to where it came from, who made it, where they came from and how the place and it's history affected it all.

Also considering nobody is going to be travelling to Spain even vaguely in the near future, this might be a nice way of widening it out and exploring the horizon over the one you have somehow.

**Comment by jkosem** [comment]
The job, especially now, is to educate about the place I think

**Comment by jkosem** [comment]
Still think this could work in a way. Would have to be just linked to map (v.MVP) from bottle? Or just link to geo-enabled web page (mobile) where they can just poke around. I imagine that each of the POIs should be tappable rather than just geo-activated.

**Comment by JGL** [comment]
Love the bottle or pork product idea!

**Comment by jkosem** [comment]
Yeah actually the journey would basically be the same but if starts just with a URL, or potentially them scanning a barcode/QR on a bottle of wine maybe.

**Comment by jkosem** [comment]
@JGL so this is what I was working on trying to think through this

![Slice](https://user-images.githubusercontent.com/495102/91452812-51421f80-e87f-11ea-93cf-a838973c30b7.png)

**Comment by jkosem** [comment]
So this follows basically the same thing but geoloc is the winery let's say. The rest would be the same. There could be a 360 mode in there a la Streetview but to do so would be massive, but we could mock it up. In real life they would need to 360 photo those on site and then you could do it though. In theory when they're doing excavation they could or would be anyhow.

**Comment by JGL** [comment]
Love it! Also a good reason to go on a research trip to all the wineries. I like the idea of being able to give local pork and wine producers stickers to attach to their produce. What do you think?

**Comment by jkosem** [comment]
Right on. Yes of course there needs to be a field trip at some point. When is another story of course. @apluskowski Any rough gueses? 2022?

**Comment by apluskowski** [comment]
We hope to be out in the field from at least June through to October this year, and for large parts of next year as well. Basically as soon as we can get out there we'll go, but it's difficult to predict too far ahead. It would be good to test it this summer, as I was planning to write an article for on this for Digital Applications in Archaeology and Cultural Heritage later in the autumn, with both of you as co-authors of course!

**Comment by apluskowski** [comment]
Re. stickers - yes, perhaps a QR code that links to the app?

**Comment by jkosem** [comment]
Potentially yes with QR codes which luckily became normalised during the pandemic. They’re a nice way to bride physical-digital.
