### ISSUE TITLE
Defining the audience

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#5]
Related to #4, we should and should have ages ago sorted out who the user is or at least defined a couple of user types (dare I say personas), let's say 3, who we would be designing for.

**Comment by JGL** [comment]
Great! Can you do it? Shall we start using the wiki? Or perhaps making a chain of .md files in the repo is best?

**Comment by jkosem** [comment]
Just assigned self. Yeah, maybe wiki is easiest.

**Comment by jkosem** [comment]
@JGL https://github.com/JGL/WalkingTourClient/wiki/Who-we-are-designing-for

Started it. I'll ping Aleks as well see if he has anything to add.
