### ISSUE TITLE
Vectary

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#6]
https://www.vectary.com/3d-modeling-news/the-vectary-viewer-now-supports-ar-on-both-iphones-and-androids/

**Comment by JGL** [comment]
Seems to me to be just object placement? Not any geolocation?

**Comment by jkosem** [comment]
Yeah exactly. I don't know, they just seemed to have figured out putting AR on a web page. I think this is now way more standard or can be done other ways.
