### ISSUE TITLE
Visitor journey MVP design

### ISSUE THREAD

**Issue by jkosem** [JGL/WalkingTourClient#9]
@JGL Something like this?

<img width="1383" alt="Screenshot 2020-08-06 at 15 06 22" src="https://user-images.githubusercontent.com/495102/89535222-68e53580-d7f6-11ea-8fdb-59dcf067d241.png">

**Comment by jkosem** [comment]
@JGL What do you think?

**Comment by jkosem** [comment]
Sort out media pop-up thing

- [ ] What happens when it's a sound file?

**Comment by JGL** [comment]
Sound files are fine too, I've just only prototyped with images for now. I'll add that as a todo.

**Comment by jkosem** [comment]
Okay cool. @JGL You cool with closing this then? Meaning as MVP it's okay?

**Comment by JGL** [comment]
Apart from the satellite photography, yes!
